### Title: NYC Restaurant Inspection Results Analysis
### Dataset: DOHMH New York City Restaurant Inspection Results
This notebook performs an exploratory analysis of a NYC restaurant inspection dataset.

In [4]:
import pandas as pd

df = pd.read_csv('DOHMH_New_York_City_Restaurant_Inspection_Results_20260426.csv')
print("Dataset loaded successfully with " + str(len(df)) + " rows.")

C:\Users\flipp\AppData\Local\Temp\ipykernel_3060\769630978.py:3: DtypeWarning: Columns (0: PHONE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('DOHMH_New_York_City_Restaurant_Inspection_Results_20260426.csv')

Dataset loaded successfully with 296352 rows.

### Dataset Shape

In [5]:
df.shape

(296352, 27)

### Column Names

In [6]:
df.columns

Index(['CAMIS', 'DBA', 'BORO', 'BUILDING', 'STREET', 'ZIPCODE', 'PHONE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'RECORD DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Community Board', 'Council District', 'Census Tract', 'BIN', 'BBL',
       'NTA', 'Location'],
      dtype='str')

### Data Types

In [7]:
df.dtypes

CAMIS                      int64
DBA                          str
BORO                         str
BUILDING                     str
STREET                       str
ZIPCODE                  float64
PHONE                     object
CUISINE DESCRIPTION          str
INSPECTION DATE              str
ACTION                       str
VIOLATION CODE               str
VIOLATION DESCRIPTION        str
CRITICAL FLAG                str
SCORE                    float64
GRADE                        str
GRADE DATE                   str
RECORD DATE                  str
INSPECTION TYPE              str
Latitude                 float64
Longitude                float64
Community Board          float64
Council District         float64
Census Tract             float64
BIN                      float64
BBL                      float64
NTA                          str
Location                     str
dtype: object

### Dataset Info

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296352 entries, 0 to 296351
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CAMIS                  296352 non-null  int64
 1   DBA                    296349 non-null  str
 2   BORO                   296352 non-null  str
 3   BUILDING               295368 non-null  str
 4   STREET                 296338 non-null  str
 5   ZIPCODE                293182 non-null  float64
 6   PHONE                  296272 non-null  object
 7   CUISINE DESCRIPTION    292779 non-null  str
 8   INSPECTION DATE        296352 non-null  str
 9   ACTION                 292875 non-null  str
 10  VIOLATION CODE         290520 non-null  str
 11  VIOLATION DESCRIPTION  290520 non-null  str
 12  CRITICAL FLAG          296352 non-null  str
 13  SCORE                  279350 non-null  float64
 14  GRADE                  145959 non-null  str
 15  GRADE DATE             136446 non-null  str
 16  RECORD DATE            296352 non-null  str
 17  INSPECTION TYPE        292875 non-null  str
 18  Latitude               294744 non-null  float64
 19  Longitude              294744 non-null  float64
 20  Community Board        291614 non-null  float64
 21  Council District       291644 non-null  float64
 22  Census Tract           291644 non-null  float64
 23  BIN                    290397 non-null  float64
 24  BBL                    294744 non-null  float64
 25  NTA                    291614 non-null  str
 26  Location               291614 non-null  str
dtypes: float64(9), int64(1), object(1), str(16)
memory usage: 168.4+ MB

### Description of Dataset

In [7]:
df.describe()

,CAMIS,ZIPCODE,SCORE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL
count,2.963520e+05,293182.000000,279350.000000,294744.000000,294744.000000,291614.000000,291644.000000,291644.000000,2.903970e+05,2.947440e+05
mean,4.811657e+07,10705.806721,25.321725,40.295928,-73.155039,254.620224,20.511346,29854.260921,2.583179e+06,2.475890e+09
std,3.720583e+06,617.089524,18.988082,4.175286,7.579394,130.360772,15.651061,31248.107036,1.356315e+06,1.337866e+09
min,3.007544e+07,6605.000000,0.000000,0.000000,-74.249101,101.000000,1.000000,100.000000,1.000000e+06,1.000000e+00
25%,5.000628e+07,10023.000000,12.000000,40.687066,-73.988609,106.000000,4.000000,8000.000000,1.050451e+06,1.010860e+09
50%,5.009510e+07,11101.000000,21.000000,40.732937,-73.955714,302.000000,20.000000,17300.000000,3.021632e+06,3.008010e+09
75%,5.013147e+07,11232.000000,33.000000,40.761172,-73.893529,401.000000,34.000000,42600.000000,4.011502e+06,4.006280e+09
max,5.018523e+07,69361.000000,214.000000,40.912822,0.000000,595.000000,51.000000,162100.000000,5.799501e+06,5.270001e+09

### Data Samples

In [9]:
df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
0,50173490,MTSKHETA-USA INC,Brooklyn,2812,OCEAN AVENUE,11229.0,7186761868,NaN,01/01/1900,NaN,...,NaN,40.593064,-73.950224,315.0,48.0,59200.0,3202134.0,3.074040e+09,BK17,POINT (-73.950224456691 40.593063971245)
1,50179033,AVE J PIZZA INC.,Brooklyn,1312,AVENUE J,11230.0,7326104604,NaN,01/01/1900,NaN,...,NaN,40.624988,-73.963029,314.0,44.0,53400.0,3179910.0,3.067150e+09,BK43,POINT (-73.963028669464 40.624987938755)
2,50177211,JOEY BATS CAFE,Manhattan,151,WEST 34 STREET,10001.0,9176152361,NaN,01/01/1900,NaN,...,NaN,40.750509,-73.989479,105.0,3.0,10900.0,1015219.0,1.008100e+09,MN17,POINT (-73.989479170444 40.750509164767)
3,50171910,CORNER OF 75TH,Queens,75-01,88 STREET,11385.0,6462012666,NaN,01/01/1900,NaN,...,NaN,40.707691,-73.862520,405.0,32.0,63700.0,4094397.0,4.038560e+09,QN19,POINT (-73.862520230869 40.707691233156)
4,50184429,CHEERS SMOOTHIES AND JUICES LLC,Bronx,236,EAST GUN HILL ROAD,10467.0,3478121116,NaN,01/01/1900,NaN,...,NaN,40.880105,-73.876490,207.0,11.0,42300.0,2018221.0,2.033430e+09,BX43,POINT (-73.8764900033 40.880104972011)

In [10]:
df.tail()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
296347,50120994,RUYI LANZHOU NOODLE & BUBBLE TEA,Queens,41-10A,MAIN STREET,11355.0,9175258818,Chinese,10/17/2025,Establishment Closed by DOHMH. Violations were...,...,Cycle Inspection / Re-inspection,40.757887,-73.829331,407.0,20.0,84900.0,4311722.0,4.050410e+09,QN22,POINT (-73.829330535405 40.757886907302)
296348,50112012,PARIS BAGUETTE,Queens,249-14,HORACE HARDING EXPRESSWAY,11362.0,3475027149,Bakery Products/Desserts,02/18/2026,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.760567,-73.731272,411.0,23.0,152902.0,4172803.0,4.083360e+09,QN45,POINT (-73.731271655742 40.76056746015)
296349,50108675,ROCCO'S PIZZA,Manhattan,148,8 AVENUE,10011.0,9175974030,Pizza,03/30/2026,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.741847,-74.000982,104.0,3.0,8100.0,1013845.0,1.007670e+09,MN13,POINT (-74.000981575352 40.741847174733)
296350,50111394,CHACHAWAN,Queens,881,WOODWARD AVENUE,11385.0,6462078989,Thai,11/16/2023,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.702558,-73.901717,405.0,30.0,58500.0,4083392.0,4.034840e+09,QN20,POINT (-73.901716580461 40.70255763198)
296351,50131016,VIA TOSCANA,Manhattan,344,WEST 52 STREET,10019.0,6462706179,Italian,03/27/2025,Violations were cited in the following area(s).,...,Pre-permit (Operational) / Initial Inspection,40.764252,-73.986918,104.0,3.0,13300.0,1025214.0,1.010420e+09,MN15,POINT (-73.986917535552 40.764251910383)

In [11]:
df.sample(5)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
160717,50004698,ROSEBANK PIZZA,Staten Island,1372,BAY STREET,10305.0,7184475300,Pizza,05/07/2024,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.610160,-74.063251,501.0,49.0,800.0,5043072.0,5.028630e+09,SI37,POINT (-74.063251074004 40.610160088177)
240710,50118536,PARIS OVEN BAKERY,Queens,40-06,34 AVENUE,11101.0,3475381240,Bakery Products/Desserts,06/30/2025,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.756592,-73.920717,401.0,22.0,15700.0,4430185.0,4.006738e+09,QN70,POINT (-73.920716556739 40.756592094398)
229965,50139886,TAQ,Manhattan,81,WARREN STREET,10007.0,7342248188,Tex-Mex,09/22/2025,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.715253,-74.010393,101.0,1.0,2100.0,1001428.0,1.001320e+09,MN24,POINT (-74.010392595204 40.715252673067)
190186,50161246,SUSHI COUNTER,Manhattan,521,EAST 12 STREET,10009.0,6469516415,Japanese,04/08/2025,Violations were cited in the following area(s).,...,Pre-permit (Operational) / Initial Inspection,40.728800,-73.980639,103.0,2.0,3400.0,1005230.0,1.004060e+09,MN22,POINT (-73.980639345112 40.728799680596)
58548,50130367,TWO BOOTS PIZZA,Manhattan,1243,2 AVENUE,10065.0,6468376015,Pizza,03/27/2023,Violations were cited in the following area(s).,...,Pre-permit (Operational) / Initial Inspection,40.764504,-73.961514,108.0,4.0,11800.0,1043871.0,1.014208e+09,MN31,POINT (-73.961514158981 40.76450421034)